LICENSE_FLAGS_ACCEPTED += "commercial"

IMAGE_INSTALL:append = " iproute2 net-tools bash ros-core ros-base ros-humble-vacuum-navigator"

TMPDIR = "/home/yoctouser/native-tmp"

PARALLEL_MAKE:pn-rust-llvm-native = "-j 4"
PARALLEL_MAKE:pn-rust-native = "-j 4"

